### ISSUE TITLE
Missing 'configure' script in Github repo

### ISSUE THREAD

**Issue by frankschmitt** [lausser/check_oracle_health#19]
The installation instructions in the README mention a 'configure' script - however, this is not part of the Github repo.
However, the official tarball at https://labs.consol.de/assets/downloads/nagios/check_oracle_health-3.0.2.1.tar.gz contains the script.

Please include the 'configure' script in the Github repo, as well - not every possible user has autoconf etc. installed / knows how to use it.

**Comment by lausser** [comment]
As you wrote, the **official** tarball contains everything necessary to build the final plugin. Everybody using the bleeding edge code from the git repository should at least be capable to install autoconf or build the plugin on a host where autoconf is available.

**Comment by frankschmitt** [comment]
Fair enough, but I'd suggest to at least update the README - in my opinion, the README on Github shouldn't contain references to files that are not present in the Github repo.
