### ISSUE TITLE
Error Icinga2

### ISSUE THREAD

**Issue by ManriqueGarcia** [lausser/check_oracle_health#21]
Hi, I’ve configured the plugin in icinga2 but I have an issue

Plugin Output
CRITICAL - cannot connect to ORABIPRO. install_driver(Oracle) failed: Can't load '/usr/local/lib64/perl5/auto/DBD/Oracle/Oracle.so' for module DBD::Oracle: libclntsh.so.12.1: cannot open shared object file: No such file or directory at /usr/lib64/perl5/DynaLoader.pm line 190.
at (eval 13) line 3.
Compilation failed in require at (eval 13) line 3.
Perhaps a required shared library or dll isn't installed where expected
 at /usr/lib64/nagios/plugins/check_oracle_health line 6155.

but in console the plugin run OK
[root@agmnag01 conf.d]# su - icinga
Last login: Wed Nov 15 17:12:49 GMT 2017 on pts/0
-bash-4.2$ /usr/lib64/nagios/plugins/check_oracle_health --connect EDBIMUPA --username OCCAM_CONTROL --password xxxxxx --mode enqueue-contention
CRITICAL - enqueue WF : 100.00% of the requests must wait , enqueue UL User-defined Locks: 100.00% of the requests must wait , enqueue TD : 62.50% of the requests must wait , enqueue TA Transaction Recovery: 52.94% of the requests must wait , enqueue PS Parallel Slave Synchronization: 16.89% of the requests must wait , enqueue MW : 100.00% of the requests must wait , enqueue JQ Job Queue: 75.00% of the requests must wait , enqueue FB : 33.33% of the requests must wait , enqueue DR Distributed Recovery Process: 100.00% of the requests must wait , enqueue AF : 14.29% of the requests must wait , enqueue HW High-Water Lock: 5.33% of the requests must wait , enqueue ZH : 0.00% of the requests must wait , enqueue XR : 0.00% of the requests must wait , en

**Comment by lausser** [comment]
This has absolutely nothing to do with check_oracle_health.
perl -e "use DBD::Oracle" 
will surely show the same error. Your Oracle Environment is not in the LD_LIBRARY_PATH.
ldd /usr/local/lib64/perl5/auto/DBD/Oracle/Oracle.so
will show you this.
After su - icinga, run 
echo $ORACLE_HOME
echo $LD_LIBRARY_PATH
the running Icinga process must have exact the same Environment. You probably have to set it in your init-script.
Gerhard

**Comment by ManriqueGarcia** [comment]
Thanks, I think all is correct

[root@agmnag01 conf.d]# su - icinga -s /bin/bash
Last login: Wed Nov 15 20:30:31 GMT 2017 on pts/0
-bash-4.2$ perl -e "use DBD::Oracle"
-bash-4.2$ ldd /usr/local/lib64/perl5/auto/DBD/Oracle/Oracle.so
        linux-vdso.so.1 =>  (0x00007ffd74f98000)
        libclntsh.so.12.1 =>
/home/oracle/app/oracle/product/12.1.0/client_2/lib/libclntsh.so.12.1
(0x00007feb9c9d0000)
        libclntshcore.so.12.1 =>
/home/oracle/app/oracle/product/12.1.0/client_2/lib/libclntshcore.so.12.1
(0x00007feb9c45c000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007feb9c245000)
        libm.so.6 => /lib64/libm.so.6 (0x00007feb9bf43000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007feb9bd26000)
        libnsl.so.1 => /lib64/libnsl.so.1 (0x00007feb9bb0d000)
        librt.so.1 => /lib64/librt.so.1 (0x00007feb9b905000)
        libc.so.6 => /lib64/libc.so.6 (0x00007feb9b541000)
        libmql1.so =>
/home/oracle/app/oracle/product/12.1.0/client_2/lib/libmql1.so
(0x00007feb9b2cb000)
        libipc1.so =>
/home/oracle/app/oracle/product/12.1.0/client_2/lib/libipc1.so
(0x00007feb9af4d000)
        libnnz12.so =>
/home/oracle/app/oracle/product/12.1.0/client_2/lib/libnnz12.so
(0x00007feb9a842000)
        libons.so =>
/home/oracle/app/oracle/product/12.1.0/client_2/lib/libons.so
(0x00007feb9a5fd000)
        /lib64/ld-linux-x86-64.so.2 (0x000055641ac8f000)
        libaio.so.1 => /lib64/libaio.so.1 (0x00007feb9a3fb000)
-bash-4.2$ echo $ORACLE_HOME
/home/oracle/app/oracle/product/12.1.0/client_2
-bash-4.2$ echo $LD_LIBRARY_PATH
/home/oracle/app/oracle/product/12.1.0/client_2/lib

but with icinga don't run ok

**Comment by Tontonitch** [comment]
Hello,
Using icinga2, what I do usually is some additions in the configuration file /etc/sysconfig/icinga2 (CentOS/RedHat flavors at least).
So, add the following lines adapted to your Oracle installation, restarted icinga2, and it should work then:
```
ORACLE_HOME=/u01/app/oracle/product/12.1.0/client_1
LD_LIBRARY_PATH=/u01/app/oracle/product/12.1.0/client_1/lib:/usr/local/lib
TNS_ADMIN=/u01/app/oracle/product/12.1.0/client_1/network/admin/tnsnames.ora
```

**Comment by ManriqueGarcia** [comment]
Thanks, but it's not work.

[root@agmnag01 conf.d]# cat /etc/sysconfig/icinga2
DAEMON=/usr/sbin/icinga2
ICINGA2_CONFIG_FILE=/etc/icinga2/icinga2.conf
ICINGA2_RUN_DIR=/run
ICINGA2_STATE_DIR=/var
ICINGA2_PID_FILE=$ICINGA2_RUN_DIR/icinga2/icinga2.pid
ICINGA2_ERROR_LOG=/var/log/icinga2/error.log
ICINGA2_STARTUP_LOG=/var/log/icinga2/startup.log
ICINGA2_LOG=/var/log/icinga2/icinga2.log
ICINGA2_CACHE_DIR=$ICINGA2_STATE_DIR/cache/icinga2
ICINGA2_USER=icinga
ICINGA2_GROUP=icinga
ICINGA2_COMMAND_GROUP=icingacmd
ORACLE_HOME=/u01/app/oracle/product/12.1.0/client_1
LD_LIBRARY_PATH=/u01/app/oracle/product/12.1.0/client_1/lib:/usr/local/lib
TNS_ADMIN=/u01/app/oracle/product/12.1.0/client_1/network/admin/tnsnames.ora

in the shell runs ok

-sh-4.2$ /usr/lib64/nagios/plugins/libexec/check_oracle_health --connect
"(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST =
ed02serv-scan.examad.agbar.local)(PORT = 1521)) (CONNECT_DATA = (SERVER =
DEDICATED) (SERVICE_NAME = EDBIMUPA) ) )" --username OCCAM_CONTROL
--password xxxxxx --mode enqueue-contention
CRITICAL - enqueue ZH : 50.00% of the requests must wait , enqueue XL :
64.13% of the requests must wait , enqueue WP : 16.67% of the requests must
wait , enqueue WF : 54.52% of the requests must wait , enqueue TS Temporary
Segment (also TableSpace): 36.78% of the requests must wait , enqueue TA
Transaction Recovery: 102.99% of the requests must wait , enqueue SR
Synchronized Replication: 100.00% of the requests must wait , enqueue SK :
83.17% of the requests must wait , enqueue RT Redo Thread: 50.00% of the
requests must wait , enqueue RO Object Reuse: 27.62% of the requests must
wait , enqueue PI Parallel Slaves: 64.52% of the requests must wait ,
enqueue PE ALTER SYSTEM SET PARAMETER = VALUE: 17.03% of the requests must
wait

I don't know what is the problem

**Comment by Tontonitch** [comment]
Don't know if it could help, but you could play with the PERL5LIB variable, and add it in /etc/sysconfig/icinga2.
For example: 
`PERL5LIB=/home/icinga/perl5/lib/perl5:/root/perl5/lib/perl5:/usr/share/perl5`

**Comment by ManriqueGarcia** [comment]
Thanks Yannick but this doesn't work yet.

Regards
