### ISSUE TITLE
ICINGA2 check_oracle_health CONNECTION Timeout

### ISSUE THREAD

**Issue by Graviel** [lausser/check_oracle_health#36]
Hello,

I have a big problem with one of my Database Servers. (Oracle Linux 7.8 installed)

Most of my Icinga checks are working, but the "check_oracle" AND "check_oracle_health" interrupt with  CHECK_NRPE STATE CTRITICAL:  Socket Timout after 10 seconds. Error Message.

The checks are working from the Database Server Console but not from ICINGA2 GUI or command line. 

Firewall settings are correct. 

Kind regards

**Comment by lausser** [comment]
This has nothing to do with check_oracle_health. You have to increase the timeout of your check_nrpe.

**Comment by Graviel** [comment]
Thx for the quick answer, where can I increase the check_nrpe timeout?

**Comment by lausser** [comment]
I have no idea how to configure icinga. It's your insallation so you have to know where the command definitions can be found. 
-t <timeout>
